package com.addiyon.keyboard

import androidx.compose.runtime.staticCompositionLocalOf

/** English-only copy for TextRevamp's optional AI feature. */
data class TextRevampStrings(
    val aiBack: String,
    val aiUsage: String,
    val aiCustomInstructions: String,
    val aiRephraseTitle: String,
    val aiRephraseSubtitle: String,
    val aiDescription: String,
    val aiCloseDescription: String,
    val aiQuotaFormat: String,
    val aiToneLabel: String,
    val aiStyleLabel: String,
    val aiPrivateTitle: String,
    val aiPrivateMessage: String,
    val aiEmptyTitle: String,
    val aiEmptyMessage: String,
    val aiEmptyAction: String,
    val aiSelectToneMessage: String,
    val aiAuthTitle: String,
    val aiAuthMessage: String,
    val aiAuthAction: String,
    val aiAuthSending: String,
    val aiAccountTitle: String,
    val aiWorkspaceTitle: String,
    val aiWorkspaceConnectedDescription: String,
    val aiWorkspaceDisconnectedDescription: String,
    val aiUsageTitle: String,
    val aiUsageRemaining: String,
    val aiUsageTokensRemainingFormat: String,
    val aiUsageResetTodayFormat: String,
    val aiUsageResetTomorrowFormat: String,
    val aiUsageResetDateFormat: String,
    val aiAccountSectionTitle: String,
    val aiAccountFallback: String,
    val aiAnonymousAccess: String,
    val aiAccountDisconnectedDescription: String,
    val aiSignOut: String,
    val aiSignInAction: String,
    val aiInputLabel: String,
    val aiWordCountFormat: String,
    val aiLoading: String,
    val aiCopy: String,
    val aiCopyDescription: String,
    val aiClipboardLabel: String,
    val aiCopiedMessage: String,
    val aiReplace: String,
    val aiReplaceDescription: String,
    val aiResultLabel: String,
    val aiTruncated: String,
    val aiErrorDescription: String,
    val aiErrorNeedsAuth: String,
    val aiErrorQuotaFormat: String,
    val aiErrorNoText: String,
    val aiErrorPrivateField: String,
    val aiErrorOffline: String,
    val aiErrorRateLimited: String,
    val aiErrorUnknown: String,
    val aiErrorTextChanged: String,
    val aiErrorSelectionChanged: String,
    val aiErrorReplaceFailed: String,
    val aiVariantErrorFormat: String,
    val aiVariantErrorOffline: String,
    val aiVariantErrorTryAgain: String,
    val aiVariantErrorQuota: String,
    val aiVariantErrorNeedsAuth: String,
    val aiVariantErrorNoText: String,
    val aiVariantErrorPrivateField: String,
    val aiVariantErrorUnavailable: String,
    val aiToneHumanize: String,
    val aiToneProfessional: String,
    val aiToneCasual: String,
    val aiToneFormal: String,
    val aiToneFriendly: String,
    val aiToneFixGrammar: String,
    val aiToneShorten: String,
    val aiToneSummarize: String,
    val aiAddCustomTone: String,
    val aiCustomToneTitle: String,
    val aiCustomToneDescription: String,
    val aiCustomToneNewHeading: String,
    val aiCustomToneEditHeading: String,
    val aiCustomToneTitleLabel: String,
    val aiCustomToneInstructionLabel: String,
    val aiCustomToneIconLabel: String,
    val aiCustomToneTitleFieldPlaceholder: String,
    val aiCustomToneFieldPlaceholder: String,
    val aiCustomToneSave: String,
    val aiCustomToneSaveChanges: String,
    val aiCustomToneCancel: String,
    val aiCustomToneEdit: String,
    val aiCustomToneListHeading: String,
    val aiCustomToneEmpty: String,
    val aiCustomToneRemove: String,
    val aiCustomToneError: String,
    val aiCustomToneIconAutoAwesome: String,
    val aiCustomToneIconFace: String,
    val aiCustomToneIconFavorite: String,
    val aiCustomToneIconStar: String,
    val aiCustomToneIconBolt: String,
    val aiCustomToneIconPalette: String,
    val aiCustomToneIconMusicNote: String,
    val aiCustomToneIconEmojiEmotions: String,
    val aiCustomToneIconSentimentSatisfied: String,
    val aiCustomToneIconThumbUp: String,
    val aiCustomToneIconWbSunny: String,
    val aiCustomToneIconLocalFireDepartment: String,
    val aiCustomToneIconWaterDrop: String,
    val aiCustomToneIconEco: String,
    val aiCustomToneIconPets: String,
    val aiCustomToneIconSchool: String,
    val aiCustomToneIconWorkOutline: String,
    val aiCustomToneIconAccountBalance: String,
    val aiCustomToneIconSpellcheck: String,
    val aiCustomToneIconShorten: String,
    val aiCustomToneIconSummarize: String,
    val aiCustomToneIconVerified: String,
    val aiCustomToneIconDiamond: String,
    val aiCustomToneIconRocket: String,
    val aiCustomToneIconCastle: String,
    val aiCustomToneIconTerrain: String,
    val aiCustomToneIconFlight: String,
    val aiCustomToneIconCoffee: String,
    val aiCustomToneIconIcecream: String,
    val aiCustomToneIconNightlight: String,
    val aiCustomToneIconQuestionAnswer: String,
    val aiCustomToneIconAutoStories: String,
    val aiCustomToneColorTeal: String,
    val aiCustomToneColorIndigo: String,
    val aiCustomToneColorOrange: String,
    val aiCustomToneColorPurple: String,
    val aiCustomToneColorGreen: String,
    val aiCustomToneColorRose: String,
    val aiCustomToneColorBlue: String,
    val aiCustomToneColorAmber: String,
    val aiStrengthSubtle: String,
    val aiStrengthBalanced: String,
    val aiStrengthStrong: String,
    val aiTourDescription: String,
    val aiTourExample: String,
    val aiPhraseCompletionTitle: String,
    val aiPhraseCompletionDescription: String,
    val aiPhraseCompletionSignedOut: String,
    val aiPhraseCompletionDisclosureTitle: String,
    val aiPhraseCompletionDisclosureMessage: String,
    val aiPhraseCompletionEnable: String,
    val aiPhraseCompletionNotNow: String,
    val aiPhraseCompletionIdle: String,
    val aiPhraseCompletionLoading: String,
    val aiPhraseCompletionInsert: String,
    val aiPhraseCompletionDismiss: String
)

val EnglishTextRevampStrings = TextRevampStrings(
    aiBack = "Back",
    aiUsage = "Usage",
    aiCustomInstructions = "Custom instructions",
    aiRephraseTitle = "AI rephrase",
    aiRephraseSubtitle = "Refine your words",
    aiDescription = "AI rephrase",
    aiCloseDescription = "Close AI rephrase",
    aiQuotaFormat = "%d/%d words",
    aiToneLabel = "Tone",
    aiStyleLabel = "Style",
    aiPrivateTitle = "Private field",
    aiPrivateMessage = "AI is disabled in password and private fields.",
    aiEmptyTitle = "Add more text",
    aiEmptyMessage = "Add more text to continue with AI rephrase.",
    aiEmptyAction = "Continue typing",
    aiSelectToneMessage = "Choose a tone above to get started.",
    aiAuthTitle = "Sign in to rephrase",
    aiAuthMessage = "Save your place and get more daily AI usage.",
    aiAuthAction = "Open sign in",
    aiAuthSending = "Opening sign in…",
    aiAccountTitle = "AI account",
    aiWorkspaceTitle = "Your AI workspace",
    aiWorkspaceConnectedDescription = "Rephrase with your TextRevamp account.",
    aiWorkspaceDisconnectedDescription = "Sign in to keep your AI access across devices.",
    aiUsageTitle = "Today's usage",
    aiUsageRemaining = "remaining",
    aiUsageTokensRemainingFormat = "%1\$,d of %2\$,d tokens remaining",
    aiUsageResetTodayFormat = "Resets today at %s",
    aiUsageResetTomorrowFormat = "Resets tomorrow at %s",
    aiUsageResetDateFormat = "Resets %s at %s",
    aiAccountSectionTitle = "Account",
    aiAccountFallback = "TextRevamp account",
    aiAnonymousAccess = "Anonymous access",
    aiAccountDisconnectedDescription = "Sign in for a connected experience",
    aiSignOut = "Sign out",
    aiSignInAction = "Sign in to TextRevamp",
    aiInputLabel = "Input",
    aiWordCountFormat = "%d words",
    aiLoading = "Rephrasing…",
    aiCopy = "Copy",
    aiCopyDescription = "Copy result",
    aiClipboardLabel = "AI result",
    aiCopiedMessage = "Copied",
    aiReplace = "Replace",
    aiReplaceDescription = "Replace text",
    aiResultLabel = "Result",
    aiTruncated = "Truncated",
    aiErrorDescription = "AI error",
    aiErrorNeedsAuth = "Sign in to use AI rephrase.",
    aiErrorQuotaFormat = "Daily token limit reached (%1\$,d tokens left).",
    aiErrorNoText = "No text to rephrase.",
    aiErrorPrivateField = "AI is unavailable in private fields.",
    aiErrorOffline = "You appear to be offline. Check your connection and try again.",
    aiErrorRateLimited = "Too many requests. Try again shortly.",
    aiErrorUnknown = "Something went wrong. Try again.",
    aiErrorTextChanged = "Text changed. Reopen AI and try again.",
    aiErrorSelectionChanged = "Selection changed. Reopen AI and try again.",
    aiErrorReplaceFailed = "Could not replace the text. Try again.",
    aiVariantErrorFormat = "%s: %s",
    aiVariantErrorOffline = "Offline",
    aiVariantErrorTryAgain = "Try again later",
    aiVariantErrorQuota = "Daily limit reached",
    aiVariantErrorNeedsAuth = "Sign in required",
    aiVariantErrorNoText = "No text",
    aiVariantErrorPrivateField = "Private field",
    aiVariantErrorUnavailable = "Unavailable",
    aiToneHumanize = "Humanize",
    aiToneProfessional = "Professional",
    aiToneCasual = "Casual",
    aiToneFormal = "Formal",
    aiToneFriendly = "Friendly",
    aiToneFixGrammar = "Fix grammar",
    aiToneShorten = "Shorten",
    aiToneSummarize = "Summarize",
    aiAddCustomTone = "Add custom",
    aiCustomToneTitle = "Custom instructions",
    aiCustomToneDescription = "Create reusable tone instructions you can pick from the keyboard.",
    aiCustomToneNewHeading = "New custom tone",
    aiCustomToneEditHeading = "Edit custom tone",
    aiCustomToneTitleLabel = "Title",
    aiCustomToneInstructionLabel = "Instruction",
    aiCustomToneIconLabel = "Icon",
    aiCustomToneTitleFieldPlaceholder = "Short title, e.g. Romantic",
    aiCustomToneFieldPlaceholder = "e.g. Make it sound more romantic",
    aiCustomToneSave = "Save tone",
    aiCustomToneSaveChanges = "Save changes",
    aiCustomToneCancel = "Cancel",
    aiCustomToneEdit = "Edit tone",
    aiCustomToneListHeading = "Your custom tones",
    aiCustomToneEmpty = "No custom tones yet.",
    aiCustomToneRemove = "Remove tone",
    aiCustomToneError = "Enter a title and an instruction first.",
    aiCustomToneIconAutoAwesome = "Sparkle",
    aiCustomToneIconFace = "Smile",
    aiCustomToneIconFavorite = "Heart",
    aiCustomToneIconStar = "Star",
    aiCustomToneIconBolt = "Bolt",
    aiCustomToneIconPalette = "Palette",
    aiCustomToneIconMusicNote = "Music",
    aiCustomToneIconEmojiEmotions = "Laugh",
    aiCustomToneIconSentimentSatisfied = "Content",
    aiCustomToneIconThumbUp = "Thumbs up",
    aiCustomToneIconWbSunny = "Sunny",
    aiCustomToneIconLocalFireDepartment = "Fire",
    aiCustomToneIconWaterDrop = "Calm",
    aiCustomToneIconEco = "Nature",
    aiCustomToneIconPets = "Pets",
    aiCustomToneIconSchool = "Academic",
    aiCustomToneIconWorkOutline = "Work",
    aiCustomToneIconAccountBalance = "Formal",
    aiCustomToneIconSpellcheck = "Grammar",
    aiCustomToneIconShorten = "Shorten",
    aiCustomToneIconSummarize = "Summarize",
    aiCustomToneIconVerified = "Trusted",
    aiCustomToneIconDiamond = "Luxury",
    aiCustomToneIconRocket = "Confident",
    aiCustomToneIconCastle = "Fantasy",
    aiCustomToneIconTerrain = "Adventure",
    aiCustomToneIconFlight = "Travel",
    aiCustomToneIconCoffee = "Coffee",
    aiCustomToneIconIcecream = "Fun",
    aiCustomToneIconNightlight = "Night",
    aiCustomToneIconQuestionAnswer = "Chat",
    aiCustomToneIconAutoStories = "Story",
    aiCustomToneColorTeal = "Teal",
    aiCustomToneColorIndigo = "Indigo",
    aiCustomToneColorOrange = "Orange",
    aiCustomToneColorPurple = "Purple",
    aiCustomToneColorGreen = "Green",
    aiCustomToneColorRose = "Rose",
    aiCustomToneColorBlue = "Blue",
    aiCustomToneColorAmber = "Amber",
    aiStrengthSubtle = "Subtle",
    aiStrengthBalanced = "Balanced",
    aiStrengthStrong = "Strong",
    aiTourDescription = "Use TextRevamp when you want to improve " +
        "tone, grammar, clarity, or length.",
    aiTourExample = "Draft → polished version",
    aiPhraseCompletionTitle = "Phrase completions",
    aiPhraseCompletionDescription = "Suggest the rest of a phrase or sentence while you type.",
    aiPhraseCompletionSignedOut = "Sign in to enable cloud phrase completions.",
    aiPhraseCompletionDisclosureTitle = "Enable phrase completions?",
    aiPhraseCompletionDisclosureMessage = "After you pause while typing, TextRevamp sends up to the last 512 characters to its server and paid AI provider to suggest a short continuation. Passwords, private fields, email-address fields, and apps that opt out are excluded. Suggestions are not saved as typing history, and you can turn this off at any time.",
    aiPhraseCompletionEnable = "Enable phrase completions",
    aiPhraseCompletionNotNow = "Not now",
    aiPhraseCompletionIdle = "Type something to complete the phrase",
    aiPhraseCompletionLoading = "Completing phrase…",
    aiPhraseCompletionInsert = "Insert phrase completion",
    aiPhraseCompletionDismiss = "Dismiss phrase completion"
)

val LocalTextRevampStrings = staticCompositionLocalOf { EnglishTextRevampStrings }
