package com.addiyon.keyboard

import androidx.compose.runtime.staticCompositionLocalOf

/** English-only copy for TextRevamp's optional AI feature. */
data class TextRevampStrings(
    val aiBack: String,
    val ai: String,
    val aiNewBadge: String,
    val aiRephraseTitle: String,
    val aiRephraseSubtitle: String,
    val aiDescription: String,
    val aiCloseDescription: String,
    val aiQuotaFormat: String,
    val aiToneLabel: String,
    val aiStyleLabel: String,
    val aiPrivateTitle: String,
    val aiPrivateMessage: String,
    val aiEmptyTitle: String,
    val aiEmptyMessage: String,
    val aiEmptyAction: String,
    val aiSelectToneMessage: String,
    val aiAuthTitle: String,
    val aiAuthMessage: String,
    val aiAuthAction: String,
    val aiAuthSending: String,
    val aiAccountTitle: String,
    val aiWorkspaceTitle: String,
    val aiWorkspaceConnectedDescription: String,
    val aiWorkspaceDisconnectedDescription: String,
    val aiUsageTitle: String,
    val aiUsageRemaining: String,
    val aiUsageTokensRemainingFormat: String,
    val aiUsageResetTodayFormat: String,
    val aiUsageResetTomorrowFormat: String,
    val aiUsageResetDateFormat: String,
    val aiAccountSectionTitle: String,
    val aiAccountFallback: String,
    val aiAnonymousAccess: String,
    val aiAccountDisconnectedDescription: String,
    val aiSignOut: String,
    val aiSignInAction: String,
    val aiInputLabel: String,
    val aiWordCountFormat: String,
    val aiLoading: String,
    val aiCopy: String,
    val aiCopyDescription: String,
    val aiClipboardLabel: String,
    val aiCopiedMessage: String,
    val aiReplace: String,
    val aiReplaceDescription: String,
    val aiResultLabel: String,
    val aiTruncated: String,
    val aiErrorDescription: String,
    val aiErrorNeedsAuth: String,
    val aiErrorQuotaFormat: String,
    val aiErrorNoText: String,
    val aiErrorPrivateField: String,
    val aiErrorOffline: String,
    val aiErrorRateLimited: String,
    val aiErrorUnknown: String,
    val aiErrorTextChanged: String,
    val aiErrorSelectionChanged: String,
    val aiErrorReplaceFailed: String,
    val aiVariantErrorFormat: String,
    val aiVariantErrorOffline: String,
    val aiVariantErrorTryAgain: String,
    val aiVariantErrorQuota: String,
    val aiVariantErrorNeedsAuth: String,
    val aiVariantErrorNoText: String,
    val aiVariantErrorPrivateField: String,
    val aiVariantErrorUnavailable: String,
    val aiToneHumanize: String,
    val aiToneProfessional: String,
    val aiToneCasual: String,
    val aiToneFormal: String,
    val aiToneFriendly: String,
    val aiToneFixGrammar: String,
    val aiToneShorten: String,
    val aiToneSummarize: String,
    val aiStrengthSubtle: String,
    val aiStrengthBalanced: String,
    val aiStrengthStrong: String,
    val aiTourDescription: String,
    val aiTourExample: String
)

val EnglishTextRevampStrings = TextRevampStrings(
    aiBack = "Back",
    ai = "AI",
    aiNewBadge = "NEW",
    aiRephraseTitle = "AI rephrase",
    aiRephraseSubtitle = "Refine your words",
    aiDescription = "AI rephrase",
    aiCloseDescription = "Close AI rephrase",
    aiQuotaFormat = "%d/%d words",
    aiToneLabel = "Tone",
    aiStyleLabel = "Style",
    aiPrivateTitle = "Private field",
    aiPrivateMessage = "AI is disabled in password and private fields.",
    aiEmptyTitle = "Add more text",
    aiEmptyMessage = "Add more text to continue with AI rephrase.",
    aiEmptyAction = "Continue typing",
    aiSelectToneMessage = "Choose a tone above to get started.",
    aiAuthTitle = "Sign in to rephrase",
    aiAuthMessage = "Save your place and get more daily AI usage.",
    aiAuthAction = "Open sign in",
    aiAuthSending = "Opening sign in…",
    aiAccountTitle = "AI account",
    aiWorkspaceTitle = "Your AI workspace",
    aiWorkspaceConnectedDescription = "Rephrase with your TextRevamp account.",
    aiWorkspaceDisconnectedDescription = "Sign in to keep your AI access across devices.",
    aiUsageTitle = "Today's usage",
    aiUsageRemaining = "remaining",
    aiUsageTokensRemainingFormat = "%1\$,d of %2\$,d tokens remaining",
    aiUsageResetTodayFormat = "Resets today at %s",
    aiUsageResetTomorrowFormat = "Resets tomorrow at %s",
    aiUsageResetDateFormat = "Resets %s at %s",
    aiAccountSectionTitle = "Account",
    aiAccountFallback = "TextRevamp account",
    aiAnonymousAccess = "Anonymous access",
    aiAccountDisconnectedDescription = "Sign in for a connected experience",
    aiSignOut = "Sign out",
    aiSignInAction = "Sign in to TextRevamp",
    aiInputLabel = "Input",
    aiWordCountFormat = "%d words",
    aiLoading = "Rephrasing…",
    aiCopy = "Copy",
    aiCopyDescription = "Copy result",
    aiClipboardLabel = "AI result",
    aiCopiedMessage = "Copied",
    aiReplace = "Replace",
    aiReplaceDescription = "Replace text",
    aiResultLabel = "Result",
    aiTruncated = "Truncated",
    aiErrorDescription = "AI error",
    aiErrorNeedsAuth = "Sign in to use AI rephrase.",
    aiErrorQuotaFormat = "Daily token limit reached (%1\$,d tokens left).",
    aiErrorNoText = "No text to rephrase.",
    aiErrorPrivateField = "AI is unavailable in private fields.",
    aiErrorOffline = "You appear to be offline. Check your connection and try again.",
    aiErrorRateLimited = "Too many requests. Try again shortly.",
    aiErrorUnknown = "Something went wrong. Try again.",
    aiErrorTextChanged = "Text changed. Reopen AI and try again.",
    aiErrorSelectionChanged = "Selection changed. Reopen AI and try again.",
    aiErrorReplaceFailed = "Could not replace the text. Try again.",
    aiVariantErrorFormat = "%s: %s",
    aiVariantErrorOffline = "Offline",
    aiVariantErrorTryAgain = "Try again later",
    aiVariantErrorQuota = "Daily limit reached",
    aiVariantErrorNeedsAuth = "Sign in required",
    aiVariantErrorNoText = "No text",
    aiVariantErrorPrivateField = "Private field",
    aiVariantErrorUnavailable = "Unavailable",
    aiToneHumanize = "Humanize",
    aiToneProfessional = "Professional",
    aiToneCasual = "Casual",
    aiToneFormal = "Formal",
    aiToneFriendly = "Friendly",
    aiToneFixGrammar = "Fix grammar",
    aiToneShorten = "Shorten",
    aiToneSummarize = "Summarize",
    aiStrengthSubtle = "Subtle",
    aiStrengthBalanced = "Balanced",
    aiStrengthStrong = "Strong",
    aiTourDescription = "Use TextRevamp when you want to improve " +
        "tone, grammar, clarity, or length.",
    aiTourExample = "Draft → polished version"
)

val LocalTextRevampStrings = staticCompositionLocalOf { EnglishTextRevampStrings }
